### ISSUE TITLE
Images are all broken and don't show up.

### ISSUE THREAD

**Issue by OIC-cMoLe** [Microsoft-USEduAzure/Azure-Data-Factory-Workshop#1]
I visited this for the first time and none of the images are working. It looks like either the links to the images are wrong or they no longer exist. I'm a visual learner and this is a significant issue trying to work through this workshop.

I'm speaking specifically to the "metadata-driven-pipeline.md" workshop.

**Comment by SvenAelterman** [comment]
Hi @OIC-cMoLe,
I am sorry, I don't see the images are missing from that page in the workshop.
This is the link to the first image on that page:
https://github.com/Microsoft-USEduAzure/Azure-Data-Factory-Workshop/raw/main/media/mdp-image005.png

Can you access it?

**Comment by OIC-cMoLe** [comment]
Hi @SvenAelterman,
Thank you for the message. I am able to access the picture which is why I find it odd I cannot see it on the page with all the other image links.

However, I had a thought and realized I'm viewing this through my work machine which may block aspects of the github.com site.

Trying this on my personal PC I found it did display the images as intended. So I don't think this is an issue with the page/site but my own work network. I will continue troubleshooting it from my end.

Thanks again for following up and sorry to bother you.
